//Token configuration.
module.exports = {
  // App Settings
  MONGO_URI: process.env.MONGO_URI || 'localhost',
  TOKEN_SECRET: process.env.TOKEN_AUTH_SECRET || 'YOUR SECRET FOR AUTH TOKENS',
  TOKEN_VERIFICATION_SECRET: process.env.TOKEN_VERIFICATION_SECRET || 'YOUR SECRET FOR VERIFICATION TOKENS',

  // OAuth 2.0
  FACEBOOK_SECRET: process.env.FACEBOOK_SECRET || 'YOUR_FACEBOOK_CLIENT_SECRET',
  GOOGLE_SECRET: process.env.GOOGLE_SECRET || 'YOUR_GOOGLE_CLIENT_SECRET',
  INSTAGRAM_SECRET: process.env.INSTAGRAM_SECRET || 'YOUR_INSTAGRAM_CLIENT_SECRET',


  // OAuth 1.0
  TWITTER_KEY: process.env.TWITTER_KEY || 'YOUR_TWITTER_KEY',
  TWITTER_SECRET: process.env.TWITTER_SECRET || 'YOUR_TWITTER_SECRET',

  //Database
  DATABASE_URL: process.env.DATABASE_URL || "mongodb://user:pass@url:27017/database",

  //Mailing
  LOGINHUB_EMAIL: process.env.LOGINHUB_EMAIL || "GMAIL USERNAME",
  LOGINGUB_EMAIL_PASSWORD: process.env.LOGINGUB_EMAIL_PASSWORD || "GMAIL PASSWORD",

  //SMS Services
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID || "YOUR_TWILIO_ACCOUNT_SID",
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN || "YOUR_TWILIO_AUTH_TOKEN",
  TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER || "+1...",
  PLIVO_AUTH_ID: process.env.PLIVO_AUTH_ID || "YOUR_PLIVO_AUTH_ID",
  PLIVO_AUTH_TOKEN: process.env.PLIVO_AUTH_TOKEN || "YOUR_PLIVO_AUTH_TOKEN",
  PLIVO_PHONE_NUMBER: process.env.PLIVO_PHONE_NUMBER || "1..."
};
};
